[#016] 알고리즘 등록
Boost-Coder/Backend pull request #17
Opened 2024-04-01 14:56 UTC by koomin1227

## 이슈
- #16 

## 체크리스트
- [x] 백준 아이디 기반으로 백준 정보를 들고 오도록 구현
- [x] 백준 아이디 기반으로 algorithm 테이블에 정보 저장

## 고민한 내용
- alogithm 엔티티 수정
  - rating, tier, 푼문제 정보를 추가했다. 나중에 알고리즘 점수 계산할 때 필요 할 수도 있을것 같아서 (근데 필요 없을려나? 생각해보니까 rating 이 이미 solved ac 에서 만든 점수라서 우리가 할 필요가 없을 것 같기도 하네요.) 의견 한번 남겨주세요.

- 중복등록 방지 -> 같은 아이디로 백준을 여러번 등록하는 것에 대해서 처리 했습니다.

2024-04-01 14:57 UTC, koomin1227 commented on src/algorithm/algorithm.service.ts
> +    }
나중에 점수 계산 알고리즘이 만들어지면 구현하면 될 것 같아서 미리 넣어놨어요

2024-04-01 14:58 UTC, koomin1227 commented on src/algorithm/algorithm.service.ts
> +        }
typeORM 에러를 서비스 레이어에서 잡아서 처리 했는데 더 좋은 방법 있으면 추천좀 해주십쇼

2024-04-02 10:27 UTC, namewhat99 requested changes

2024-04-02 10:27 UTC, namewhat99 commented on src/algorithm/algorithm.service.ts
> +        algorithm.point = this.calculatePoint(bojInfo);
이 객체 생성하는 부분에서 아예 Algorithm 클래스의 생성자 매개변수로 객체를 넣고 bojInfo 에서 넘어오는 정보들을 한번에 넘기면 좀 더 깔끔하게 짤 수 있지 않을까 싶네요

2024-04-02 10:27 UTC, namewhat99 commented on src/algorithm/algorithm.service.ts
> +        }
서비스에서 바꿔서 처리하는건 좋은것 같슴다. 근데 queryFailedError 이면 그냥 BadRequestException 을 던지고 그 안에 error 내용을 넣어주는건 어떠신가요? 그러면 다른 에러들에 대해서도 내용도 알 수 있고 굳이 분기해서 처리할 필요도 없어질 것 같긴 합니다

2024-04-02 10:55 UTC, koomin1227 commented on src/algorithm/algorithm.service.ts
> +        algorithm.point = this.calculatePoint(bojInfo);
Algorithm 클래스가 엔티티 클래스라서 생성자를 만들어 놓으면 에러가 떠서 코드가 안돌아갑니다 ㅠㅜ

2024-04-02 11:54 UTC, namewhat99 approved these changes

2024-04-02 11:55 UTC, merged